### ISSUE TITLE
[Badges] for some reason the npm version badges stopped working

### ISSUE THREAD

**Issue by jimdebeer** [vigour-io/doc#25]
![image](https://cloud.githubusercontent.com/assets/5682524/15287561/125633b6-1b64-11e6-8f2a-ef858d565e78.png)

**Comment by jimdebeer** [comment]
![image](https://cloud.githubusercontent.com/assets/5682524/15287751/5c13e542-1b65-11e6-970c-8453cfa36120.png)

**Comment by shawninder** [comment]
This looks fixed
