### ISSUE TITLE
[comments] doc creates comments that show in npm

### ISSUE THREAD

**Issue by youzi** [vigour-io/doc#26]
When not having a subtitle/description for you repo, npm uses the first lines of your README.md. Resulting in: https://www.npmjs.com/search?q=brisky
![image](https://cloud.githubusercontent.com/assets/5662898/15290508/326eea02-1b79-11e6-9294-f54192743df9.png)

**Comment by shawninder** [comment]
Solutions:
- Add a description to you repo (and package.json)
- Add a description to your README.md and move the badges under that description

vigour-doc can't change the behaviour of npm. The only thing I can do here is to change the docs of vigour docs to warn about this problem and make sure none of the examples shown encourage people to set things up in a way that exhibits this problem...

I can also poke the npm team about ignoring comments when getting the first line. This indeed looks like a bug in npm more than in vigour-doc to me. Or do you have another idea to solve this @youzi ?

**Comment by youzi** [comment]
@shawninder I'd say use a commenting style that is handled correctly by npm. [This](https://github.com/npm/marky-markdown/issues/42) indicates there is such a thing.

**Comment by shawninder** [comment]
@youzi I don't see any mention of another commenting style in there... They are talking about comments in markdown vs comments in html code blocks in markdown. In both cases, it's the same html-style comments starting with `<!--` and ending with `-->`.

**Comment by youzi** [comment]
Ok issue is for npm. Closing.

**Comment by shawninder** [comment]
I will close this once I've documented it and registered an issue with npm

**Comment by shawninder** [comment]
This seems to be fixed
